// Problem2.java
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

class Problem2{
  public static void main(String[] args) {
    int term1 = 0;
    int term2 = 1;
    int currentTerm = 0;
    int sum = 0;
    while(currentTerm < 4_000_000){
      currentTerm = term1 + term2;

      if(currentTerm%2 == 0){
        sum = sum + currentTerm;
      }

      term1 = term2;
      term2 = currentTerm;

    }
    System.out.println("\n" + sum);
  }
}
